language: objective-c
#xcode_workspace: sampleCaptureForIos.xcworkspace
#xcode_scheme: sampleCaptureForIos
xcode_sdk: iphonesimulator7.1

rvm: 1.9.3

# blacklist
#branches:
#  except:
#    - legacy
#    - experimental

# whitelist
branches:
  only:
    - master

before_install:
  - gem install cocoapods -v '0.32.1'

install:
  - pod install

#before_script

env:
  sauce_username: "KazuCocoa"
  sauce_access_key: #"37a03dc7-8f8e-4fa7-901f-8006db1dd07d"
        secure: "LICeBi0jJxva1YY2orphGNzpXnfGoiqWeQvMpLIVME6FV4u3lIVKIglKZKGK2jmSve6lgqXbfnIhaocrrZLM1+m6LmYsLvyM8GUl2jkSGQR2Hs/wfX8+65jtNnHAs5PCgNQw0wsrNNdqbtAA2F/BS3KL+nU+Obnqe8JHCcBIZIo="

rvm: 2.1.0

script:
  - ./travis_build.sh
  - bundle install
  - rspec test.rb


#after_success or after_failure

#after_success:


after_script:


