language: objective-c
#xcode_workspace: sampleCaptureForIos.xcworkspace
#xcode_scheme: sampleCaptureForIos
xcode_sdk: iphonesimulator7.1

rvm: 1.9.3

# blacklist
#branches:
#  except:
#    - legacy
#    - experimental

# whitelist
branches:
  only:
    - master

before_install:
  - gem install cocoapods -v '0.32.1'

install:
  - pod install

#before_script

env:
  SAUCE_USERNAME="KazuCocoa"
  SAUCE_ACCESS_KEY: #"37a03dc7-8f8e-4fa7-901f-8006db1dd07d"
        secure: "Kh3Se6QQ2Oez7vHLFpTcXHGaSxbEV5KCbGGIen/jRu4taMrt6MMVcFdb1RXps2pU8JgbbsJzgHaNv24jC+02wRlTaHA6Zx3JLDV3+YpEhYDJBqXjlSA6TpItsS6Szg+PqAdomLdcFYhCAj5/SJjIi6Iq8aPVoITQMQxKS8ipgFU="

rvm: 2.1.0

script:
  - ./travis_build.sh
  - bundle install
  - rspec test.rb


#after_success or after_failure

#after_success:


after_script:


