language: objective-c
#xcode_workspace: sampleCaptureForIos.xcworkspace
#xcode_scheme: sampleCaptureForIos
xcode_sdk: iphonesimulator7.1

rvm: 1.9.3

# blacklist
#branches:
#  except:
#    - legacy
#    - experimental

addons:
  sauce_connect: true


# whitelist
branches:
  only:
    - master

before_install:
  - gem install cocoapods -v '0.32.1'

install:
  - pod install

#before_script

script:
  - ./travis_build.sh

#after_success or after_failure

after_success:
#  - upload apk files to somewhere (We should integrate other storage service or deploygate, for example.)
  - test.rb SAUCE_USERNAME="KazuCocoa" SAUCE_ACCESS_KEY="37a03dc7-8f8e-4fa7-901f-8006db1dd07d"

#after_script


